
  const BookData = {
    "fiction": [
      {
        "id": "F001",
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "isbn": "978-0-06-112008-4",
        "image": "http://books.google.com/books/content?id=PGR2AwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.3,
        "year_published": 2011,
        "pages": 374,
        "language": "English",
        "publisher": "Crown Publishers",
        "genre": "Virtual Reality, Dystopian",
        "availability": "available",
        "location": "G-07-SF",
        "description": "A virtual reality treasure hunt in a dystopian future."
      },
      {
        "id": "F002",
        "title": "1984",
        "author": "George Orwell",
        "isbn": "978-0-452-28423-4",
        "image": "http://books.google.com/books/content?id=4HQcMQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1949,
        "pages": 328,
        "language": "English",
        "publisher": "Secker & Warburg",
        "genre": "Dystopian Fiction",
        "availability": "checked_out",
        "location": "A-15-F",
        "description": "A dystopian vision of totalitarian control and surveillance."
      },
      {
        "id": "F003",
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "isbn": "978-0-14-143951-8",
        "image": "http://books.google.com/books/content?id=mxDLY0qL2mAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.3,
        "year_published": 1813,
        "pages": 432,
        "language": "English",
        "publisher": "T. Egerton",
        "genre": "Romance, Satire",
        "availability": "available",
        "location": "B-03-F",
        "description": "A witty exploration of love, marriage, and social class in Georgian England."
      },
      {
        "id": "F004",
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "isbn": "978-0-7432-7356-5",
        "image": "http://books.google.com/books/content?id=HestSXO362YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1925,
        "pages": 180,
        "language": "English",
        "publisher": "Charles Scribner's Sons",
        "genre": "Literary Fiction",
        "availability": "available",
        "location": "B-07-F",
        "description": "The tragic story of Jay Gatsby's pursuit of the American Dream."
      },
      {
        "id": "F005",
        "title": "One Hundred Years of Solitude",
        "author": "Gabriel García Márquez",
        "isbn": "978-0-06-088328-7",
        "image": "http://books.google.com/books/content?id=RyGVAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1967,
        "pages": 417,
        "language": "Spanish",
        "publisher": "Harper & Row",
        "genre": "Magical Realism",
        "availability": "available",
        "location": "C-01-F",
        "description": "A multi-generational saga of the Buendía family in the fictional town of Macondo."
      },
      {
        "id": "F006",
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "isbn": "978-0-316-76948-0",
        "image": "http://books.google.com/books/content?id=mZunDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.8,
        "year_published": 1951,
        "pages": 277,
        "language": "English",
        "publisher": "Little, Brown and Company",
        "genre": "Coming-of-age Fiction",
        "availability": "checked_out",
        "location": "C-05-F",
        "description": "Holden Caulfield's journey through New York City and adolescent alienation."
      },
      {
        "id": "F007",
        "title": "Lord of the Flies",
        "author": "William Golding",
        "isbn": "978-0-571-05686-2",
        "image": "http://books.google.com/books/content?id=3KRdJZbAN_sC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.7,
        "year_published": 1954,
        "pages": 224,
        "language": "English",
        "publisher": "Faber & Faber",
        "genre": "Allegorical Fiction",
        "availability": "available",
        "location": "C-09-F",
        "description": "A group of British boys stranded on an uninhabited island and their struggle for power."
      },
      {
        "id": "F008",
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "isbn": "978-1-59448-000-3",
        "image": "http://books.google.com/books/content?id=KUMIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.3,
        "year_published": 2003,
        "pages": 371,
        "language": "English",
        "publisher": "Riverhead Books",
        "genre": "Historical Fiction",
        "availability": "available",
        "location": "D-02-F",
        "description": "A story of friendship and redemption set against the backdrop of Afghanistan's tumultuous history."
      },
      {
        "id": "F009",
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "isbn": "978-0-375-84220-7",
        "image": "http://books.google.com/books/content?id=_MnZAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.4,
        "year_published": 2005,
        "pages": 552,
        "language": "English",
        "publisher": "Picador",
        "genre": "Historical Fiction",
        "availability": "available",
        "location": "D-06-F",
        "description": "Narrated by Death, this is the story of Liesel Meminger in Nazi Germany."
      },
      {
        "id": "F010",
        "title": "Beloved",
        "author": "Toni Morrison",
        "isbn": "978-1-4000-3341-6",
        "image": "http://books.google.com/books/content?id=sfmp6gjZGP8C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 3.9,
        "year_published": 1987,
        "pages": 324,
        "language": "English",
        "publisher": "Alfred A. Knopf",
        "genre": "Historical Fiction, Magical Realism",
        "availability": "available",
        "location": "D-10-F",
        "description": "A haunting tale of slavery and its aftermath in post-Civil War Ohio."
      },
      {
        "id": "F011",
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "isbn": "978-0-385-49081-8",
        "image": "http://books.google.com/books/content?id=UZs9sbk5gO0C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1985,
        "pages": 311,
        "language": "English",
        "publisher": "McClelland & Stewart",
        "genre": "Dystopian Fiction",
        "availability": "checked_out",
        "location": "E-01-F",
        "description": "A chilling vision of a theocratic dystopia where women's rights are stripped away."
      },
      {
        "id": "F012",
        "title": "Crime and Punishment",
        "author": "Fyodor Dostoevsky",
        "isbn": "978-0-14-044913-6",
        "image": "http://books.google.com/books/content?id=0HZrq-4zA5QC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.2,
        "year_published": 1866,
        "pages": 671,
        "language": "Russian",
        "publisher": "The Russian Messenger",
        "genre": "Philosophical Fiction",
        "availability": "available",
        "location": "E-05-F",
        "description": "The psychological journey of Raskolnikov after committing murder."
      },
      {
        "id": "F013",
        "title": "The Color Purple",
        "author": "Alice Walker",
        "isbn": "978-0-15-119554-9",
        "image": "http://books.google.com/books/content?id=ZIogAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1982,
        "pages": 295,
        "language": "English",
        "publisher": "Harcourt Brace Jovanovich",
        "genre": "Epistolary Fiction",
        "availability": "available",
        "location": "E-09-F",
        "description": "Celie's journey from oppression to self-discovery in the American South."
      },
      {
        "id": "F014",
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "isbn": "978-0-06-085052-4",
        "image": "http://books.google.com/books/content?id=3PabEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1932,
        "pages": 268,
        "language": "English",
        "publisher": "Chatto & Windus",
        "genre": "Dystopian Fiction",
        "availability": "available",
        "location": "F-03-F",
        "description": "A society controlled by technology, conditioning, and artificial happiness."
      },
      {
        "id": "F015",
        "title": "Jane Eyre",
        "author": "Charlotte Brontë",
        "isbn": "978-0-14-144114-6",
        "image": "http://books.google.com/books/content?id=lSMGAAAAQAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1847,
        "pages": 507,
        "language": "English",
        "publisher": "Smith, Elder & Co.",
        "genre": "Gothic Romance",
        "availability": "available",
        "location": "F-07-F",
        "description": "The story of an orphaned girl who becomes a governess and finds love."
      },
      {
        "id": "F016",
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "isbn": "978-0-06-231500-7",
        "image": "http://books.google.com/books/content?id=K3KODwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1988,
        "pages": 163,
        "language": "Portuguese",
        "publisher": "HarperCollins",
        "genre": "Quest, Philosophical Fiction",
        "availability": "available",
        "location": "F-11-F",
        "description": "A young shepherd's journey to find treasure and discover his personal legend."
      },
      {
        "id": "F017",
        "title": "Wuthering Heights",
        "author": "Emily Brontë",
        "isbn": "978-0-14-143955-6",
        "image": "http://books.google.com/books/content?id=S2Yvf-tWNdUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1847,
        "pages": 416,
        "language": "English",
        "publisher": "Thomas Cautley Newby",
        "genre": "Gothic Romance",
        "availability": "checked_out",
        "location": "G-01-F",
        "description": "A tale of passionate and destructive love on the Yorkshire moors."
      },
      {
        "id": "F018",
        "title": "The Picture of Dorian Gray",
        "author": "Oscar Wilde",
        "isbn": "978-0-14-143957-0",
        "image": "http://books.google.com/books/content?id=icSwNbJng4wC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1890,
        "pages": 254,
        "language": "English",
        "publisher": "Ward, Lock & Co.",
        "genre": "Gothic Fiction",
        "availability": "available",
        "location": "G-05-F",
        "description": "A man's portrait ages while he remains young, exploring themes of vanity and moral corruption."
      },
      {
        "id": "F019",
        "title": "Gone with the Wind",
        "author": "Margaret Mitchell",
        "isbn": "978-1-4516-3534-0",
        "image": "http://books.google.com/books/content?id=01KdDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.3,
        "year_published": 1936,
        "pages": 1037,
        "language": "English",
        "publisher": "Macmillan Publishers",
        "genre": "Historical Romance",
        "availability": "available",
        "location": "G-09-F",
        "description": "Scarlett O'Hara's story during the Civil War and Reconstruction era."
      },
      {
        "id": "F020",
        "title": "Anna Karenina",
        "author": "Leo Tolstoy",
        "isbn": "978-0-14-303500-4",
        "image": "http://books.google.com/books/content?id=YmhDLD9UsPQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1877,
        "pages": 864,
        "language": "Russian",
        "publisher": "The Russian Messenger",
        "genre": "Literary Fiction",
        "availability": "available",
        "location": "H-02-F",
        "description": "A complex tale of love, society, and morality in 19th-century Russia."
      },
      {
        "id": "F021",
        "title": "The Sun Also Rises",
        "author": "Ernest Hemingway",
        "isbn": "978-0-7432-9733-2",
        "image": "http://books.google.com/books/content?id=_-KBsJuQaCgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.8,
        "year_published": 1926,
        "pages": 251,
        "language": "English",
        "publisher": "Charles Scribner's Sons",
        "genre": "Modernist Literature",
        "availability": "available",
        "location": "H-06-F",
        "description": "The Lost Generation's journey through post-WWI Europe."
      },
      {
        "id": "F022",
        "title": "Of Mice and Men",
        "author": "John Steinbeck",
        "isbn": "978-0-14-017739-8",
        "image": "http://books.google.com/books/content?id=TYB5AAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1937,
        "pages": 112,
        "language": "English",
        "publisher": "Covici Friede",
        "genre": "Tragedy, Realist Fiction",
        "availability": "available",
        "location": "H-10-F",
        "description": "Two displaced migrant ranch workers during the Great Depression."
      },
      {
        "id": "F023",
        "title": "The Adventures of Huckleberry Finn",
        "author": "Mark Twain",
        "isbn": "978-0-14-243717-4",
        "image": "http://books.google.com/books/content?id=s9q60rLUbRcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.8,
        "year_published": 1884,
        "pages": 366,
        "language": "English",
        "publisher": "Chatto & Windus",
        "genre": "Picaresque Fiction",
        "availability": "checked_out",
        "location": "I-01-F",
        "description": "Huck Finn's journey down the Mississippi River with runaway slave Jim."
      },
      {
        "id": "F024",
        "title": "Slaughterhouse-Five",
        "author": "Kurt Vonnegut",
        "isbn": "978-0-385-31208-0",
        "image": "http://books.google.com/books/content?id=WKdcCgk_FowC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1969,
        "pages": 275,
        "language": "English",
        "publisher": "Delacorte Press",
        "genre": "Dark Comedy, Anti-war",
        "availability": "available",
        "location": "I-05-F",
        "description": "Billy Pilgrim's experience as a prisoner of war and his time travel adventures."
      },
      {
        "id": "F025",
        "title": "The Grapes of Wrath",
        "author": "John Steinbeck",
        "isbn": "978-0-14-303943-9",
        "image": "http://books.google.com/books/content?id=brHqUgNgfkQC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4,
        "year_published": 1939,
        "pages": 464,
        "language": "English",
        "publisher": "The Viking Press",
        "genre": "Social Realism",
        "availability": "available",
        "location": "I-09-F",
        "description": "The Joad family's migration from Oklahoma to California during the Dust Bowl."
      },
      {
        "id": "F026",
        "title": "A Tale of Two Cities",
        "author": "Charles Dickens",
        "isbn": "978-0-14-143960-0",
        "image": "http://books.google.com/books/content?id=TnAV0KYzkrwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.8,
        "year_published": 1859,
        "pages": 489,
        "language": "English",
        "publisher": "Chapman & Hall",
        "genre": "Historical Fiction",
        "availability": "available",
        "location": "J-02-F",
        "description": "Set in London and Paris before and during the French Revolution."
      },
      {
        "id": "F027",
        "title": "Moby-Dick",
        "author": "Herman Melville",
        "isbn": "978-0-14-243724-2",
        "image": "http://books.google.com/books/content?id=XV8XAAAAYAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.5,
        "year_published": 1851,
        "pages": 635,
        "language": "English",
        "publisher": "Richard Bentley",
        "genre": "Adventure Fiction",
        "availability": "available",
        "location": "J-06-F",
        "description": "Captain Ahab's obsessive quest for revenge against the white whale."
      },
      {
        "id": "F028",
        "title": "The Brothers Karamazov",
        "author": "Fyodor Dostoevsky",
        "isbn": "978-0-14-044924-2",
        "image": "http://books.google.com/books/content?id=OG0e6djUgUYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.3,
        "year_published": 1880,
        "pages": 824,
        "language": "Russian",
        "publisher": "The Russian Messenger",
        "genre": "Philosophical Fiction",
        "availability": "available",
        "location": "J-10-F",
        "description": "A philosophical novel exploring faith, doubt, and morality through a murder mystery."
      },
      {
        "id": "F029",
        "title": "One Flew Over the Cuckoo's Nest",
        "author": "Ken Kesey",
        "isbn": "978-0-14-118123-4",
        "image": "http://books.google.com/books/content?id=UlIrAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1962,
        "pages": 325,
        "language": "English",
        "publisher": "Viking Press",
        "genre": "Psychological Fiction",
        "availability": "available",
        "location": "K-01-F",
        "description": "McMurphy's rebellion against the oppressive mental hospital system."
      },
      {
        "id": "F030",
        "title": "The Outsiders",
        "author": "S.E. Hinton",
        "isbn": "978-0-14-038572-4",
        "image": "http://books.google.com/books/content?id=ceksEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1967,
        "pages": 192,
        "language": "English",
        "publisher": "Viking Press",
        "genre": "Coming-of-age Fiction",
        "availability": "checked_out",
        "location": "K-05-F",
        "description": "Ponyboy Curtis and the struggle between social classes in 1960s Oklahoma."
      }
    ],
    "non_fiction": [
      {
        "id": "NF001",
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "isbn": "978-0-06-231609-7",
        "image": "http://books.google.com/books/content?id=1EiJAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.4,
        "year_published": 2011,
        "pages": 443,
        "language": "Hebrew",
        "publisher": "Harper",
        "genre": "History, Anthropology",
        "availability": "available",
        "location": "A-01-NF",
        "description": "An exploration of how Homo sapiens became the dominant species on Earth."
      },
      {
        "id": "NF002",
        "title": "Educated",
        "author": "Tara Westover",
        "isbn": "978-0-399-59050-4",
        "image": "http://books.google.com/books/content?id=xegpswEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.5,
        "year_published": 2018,
        "pages": 334,
        "language": "English",
        "publisher": "Random House",
        "genre": "Memoir",
        "availability": "available",
        "location": "A-05-NF",
        "description": "A memoir about education and the struggle for self-invention."
      },
      {
        "id": "NF003",
        "title": "The Immortal Life of Henrietta Lacks",
        "author": "Rebecca Skloot",
        "isbn": "978-1-4000-5217-2",
        "image": "http://books.google.com/books/content?id=tzlqDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 2010,
        "pages": 381,
        "language": "English",
        "publisher": "Crown Publishing Group",
        "genre": "Science, Biography",
        "availability": "checked_out",
        "location": "A-09-NF",
        "description": "The story of how one woman's cells revolutionized medical science."
      },
      {
        "id": "NF004",
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "isbn": "978-0-374-53355-7",
        "image": "http://books.google.com/books/content?id=oV1tXT3HigoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.2,
        "year_published": 2011,
        "pages": 499,
        "language": "English",
        "publisher": "Farrar, Straus and Giroux",
        "genre": "Psychology, Behavioral Economics",
        "availability": "available",
        "location": "B-02-NF",
        "description": "An exploration of the two systems that drive the way we think."
      },
      {
        "id": "NF005",
        "title": "The Power of Habit",
        "author": "Charles Duhigg",
        "isbn": "978-1-4000-6928-6",
        "image": "http://books.google.com/books/content?id=oFYNngEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 2012,
        "pages": 371,
        "language": "English",
        "publisher": "Random House",
        "genre": "Psychology, Self-Help",
        "availability": "available",
        "location": "B-06-NF",
        "description": "Why habits exist and how they can be changed."
      },
      {
        "id": "NF006",
        "title": "Becoming",
        "author": "Michelle Obama",
        "isbn": "978-1-5247-6313-8",
        "image": "http://books.google.com/books/content?id=rMGoDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.5,
        "year_published": 2018,
        "pages": 448,
        "language": "English",
        "publisher": "Crown Publishing Group",
        "genre": "Memoir, Biography",
        "availability": "available",
        "location": "B-10-NF",
        "description": "The former First Lady's deeply personal account of her life."
      },
      {
        "id": "NF007",
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "isbn": "978-0-553-38016-3",
        "image": "http://books.google.com/books/content?id=iOBT0qN8DKUC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1988,
        "pages": 256,
        "language": "English",
        "publisher": "Bantam Doubleday Dell",
        "genre": "Physics, Cosmology",
        "availability": "available",
        "location": "C-01-NF",
        "description": "Hawking's attempt to explain cosmology to the general public."
      },
      {
        "id": "NF008",
        "title": "The 7 Habits of Highly Effective People",
        "author": "Stephen R. Covey",
        "isbn": "978-1-982-13719-5",
        "image": "http://books.google.com/books/content?id=upUxaNWSaRIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1989,
        "pages": 381,
        "language": "English",
        "publisher": "Free Press",
        "genre": "Self-Help, Business",
        "availability": "checked_out",
        "location": "C-05-NF",
        "description": "A holistic approach for solving personal and professional problems."
      },
      {
        "id": "NF009",
        "title": "Freakonomics",
        "author": "Steven D. Levitt, Stephen J. Dubner",
        "isbn": "978-0-06-073132-6",
        "image": "http://books.google.com/books/content?id=kxsQhM4D8uIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2005,
        "pages": 315,
        "language": "English",
        "publisher": "William Morrow",
        "genre": "Economics, Social Science",
        "availability": "available",
        "location": "C-09-NF",
        "description": "A rogue economist explores the hidden side of everything."
      },
      {
        "id": "NF010",
        "title": "The Lean Startup",
        "author": "Eric Ries",
        "isbn": "978-0-307-88789-4",
        "image": "http://books.google.com/books/content?id=tvfyz-4JILwC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 2011,
        "pages": 336,
        "language": "English",
        "publisher": "Crown Business",
        "genre": "Business, Entrepreneurship",
        "availability": "available",
        "location": "D-03-NF",
        "description": "How today's entrepreneurs use continuous innovation to create radically successful businesses."
      },
      {
        "id": "NF011",
        "title": "Quiet: The Power of Introverts",
        "author": "Susan Cain",
        "isbn": "978-0-307-35214-9",
        "image": "http://books.google.com/books/content?id=O6gZJa9kdlYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 2012,
        "pages": 333,
        "language": "English",
        "publisher": "Crown Publishers",
        "genre": "Psychology, Self-Help",
        "availability": "available",
        "location": "D-07-NF",
        "description": "The power of introverts in a world that can't stop talking."
      },
      {
        "id": "NF012",
        "title": "The Devil Wears Prada",
        "author": "Lauren Weisberger",
        "isbn": "978-0-7679-1476-8",
        "image": "http://books.google.com/books/content?id=i7weTA29ke4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.7,
        "year_published": 2003,
        "pages": 360,
        "language": "English",
        "publisher": "Doubleday",
        "genre": "Memoir, Fashion",
        "availability": "available",
        "location": "D-11-NF",
        "description": "A young woman's experience working for a demanding fashion magazine editor."
      },
      {
        "id": "NF013",
        "title": "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "isbn": "978-0-8070-1427-1",
        "image": "http://books.google.com/books/content?id=H8k4JLZu6AsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.4,
        "year_published": 1946,
        "pages": 165,
        "language": "German",
        "publisher": "Beacon Press",
        "genre": "Psychology, Philosophy",
        "availability": "available",
        "location": "E-02-NF",
        "description": "A Holocaust survivor's reflections on finding meaning in suffering."
      },
      {
        "id": "NF014",
        "title": "Atomic Habits",
        "author": "James Clear",
        "isbn": "978-0-7352-1129-2",
        "image": "http://books.google.com/books/content?id=yzFYEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.4,
        "year_published": 2018,
        "pages": 320,
        "language": "English",
        "publisher": "Avery",
        "genre": "Self-Help, Psychology",
        "availability": "checked_out",
        "location": "E-06-NF",
        "description": "An easy and proven way to build good habits and break bad ones."
      },
      {
        "id": "NF015",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "isbn": "978-1-59030-963-7",
        "image": "http://books.google.com/books/content?id=3dY4DgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": -500,
        "pages": 273,
        "language": "Chinese",
        "publisher": "Dover Publications",
        "genre": "Military Strategy, Philosophy",
        "availability": "available",
        "location": "E-10-NF",
        "description": "Ancient Chinese military treatise on strategy and tactics."
      },
      {
        "id": "NF016",
        "title": "Into the Wild",
        "author": "Jon Krakauer",
        "isbn": "978-0-385-48680-4",
        "image": "http://books.google.com/books/content?id=m9BiDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1996,
        "pages": 207,
        "language": "English",
        "publisher": "Villard Books",
        "genre": "Adventure, Biography",
        "availability": "available",
        "location": "F-04-NF",
        "description": "The true story of Christopher McCandless's Alaskan adventure."
      },
      {
        "id": "NF017",
        "title": "The Tipping Point",
        "author": "Malcolm Gladwell",
        "isbn": "978-0-316-31696-8",
        "image": "http://books.google.com/books/content?id=mUZ7EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2000,
        "pages": 301,
        "language": "English",
        "publisher": "Little, Brown and Company",
        "genre": "Sociology, Psychology",
        "availability": "available",
        "location": "F-08-NF",
        "description": "How little things can make a big difference."
      },
      {
        "id": "NF018",
        "title": "Outliers",
        "author": "Malcolm Gladwell",
        "isbn": "978-0-316-01792-3",
        "image": "http://books.google.com/books/content?id=ialrgIT41OAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 2008,
        "pages": 309,
        "language": "English",
        "publisher": "Little, Brown and Company",
        "genre": "Psychology, Sociology",
        "availability": "available",
        "location": "F-12-NF",
        "description": "The story of success and what makes high-achievers different."
      },
      {
        "id": "NF019",
        "title": "Born to Run",
        "author": "Christopher McDougall",
        "isbn": "978-0-307-27918-7",
        "image": "http://books.google.com/books/content?id=n3ANAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 2009,
        "pages": 287,
        "language": "English",
        "publisher": "Alfred A. Knopf",
        "genre": "Sports, Adventure",
        "availability": "available",
        "location": "G-03-NF",
        "description": "A hidden tribe, superathletes, and the greatest race the world has never seen."
      },
      {
        "id": "NF020",
        "title": "The Diary of a Young Girl",
        "author": "Anne Frank",
        "isbn": "978-0-553-29698-1",
        "image": "http://books.google.com/books/content?id=EO-2vZseBf0C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1947,
        "pages": 283,
        "language": "Dutch",
        "publisher": "Contact Publishing",
        "genre": "Autobiography, Historical",
        "availability": "available",
        "location": "G-07-NF",
        "description": "The diary of a Jewish teenager hiding during the Holocaust."
      },
      {
        "id": "NF021",
        "title": "Steve Jobs",
        "author": "Walter Isaacson",
        "isbn": "978-1-4516-4853-1",
        "image": "http://books.google.com/books/content?id=8U2oAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.4,
        "year_published": 2011,
        "pages": 656,
        "language": "English",
        "publisher": "Simon & Schuster",
        "genre": "Biography, Technology",
        "availability": "checked_out",
        "location": "G-11-NF",
        "description": "The exclusive biography of Apple's co-founder."
      },
      {
        "id": "NF022",
        "title": "The Four Agreements",
        "author": "Don Miguel Ruiz",
        "isbn": "978-1-878424-31-0",
        "image": "http://books.google.com/books/content?id=KeFdEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.2,
        "year_published": 1997,
        "pages": 138,
        "language": "English",
        "publisher": "Amber-Allen Publishing",
        "genre": "Spirituality, Self-Help",
        "availability": "available",
        "location": "H-04-NF",
        "description": "A practical guide to personal freedom based on ancient Toltec wisdom."
      },
      {
        "id": "NF023",
        "title": "Guns, Germs, and Steel",
        "author": "Jared Diamond",
        "isbn": "978-0-393-31755-8",
        "image": "http://books.google.com/books/content?id=1lBu_bqSsSMC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4,
        "year_published": 1997,
        "pages": 518,
        "language": "English",
        "publisher": "W. W. Norton & Company",
        "genre": "History, Anthropology",
        "availability": "available",
        "location": "H-08-NF",
        "description": "The fates of human societies and how geography shaped civilization."
      },
      {
        "id": "NF024",
        "title": "Eat, Pray, Love",
        "author": "Elizabeth Gilbert",
        "isbn": "978-0-14-303841-8",
        "image": "http://books.google.com/books/content?id=EbquUB1D6B8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.6,
        "year_published": 2006,
        "pages": 334,
        "language": "English",
        "publisher": "Viking Press",
        "genre": "Memoir, Travel",
        "availability": "available",
        "location": "H-12-NF",
        "description": "One woman's search for everything across Italy, India, and Indonesia."
      },
      {
        "id": "NF025",
        "title": "The Signal and the Noise",
        "author": "Nate Silver",
        "isbn": "978-0-14-312508-2",
        "image": "http://books.google.com/books/content?id=SI-VqAT4_hYC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 3.9,
        "year_published": 2012,
        "pages": 544,
        "language": "English",
        "publisher": "Penguin Press",
        "genre": "Statistics, Data Science",
        "availability": "available",
        "location": "I-05-NF",
        "description": "Why so many predictions fail—but some don't."
      },
      {
        "id": "NF026",
        "title": "Wild",
        "author": "Cheryl Strayed",
        "isbn": "978-0-307-59273-6",
        "image": "http://books.google.com/books/content?id=OPgVpIZ71iAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2012,
        "pages": 315,
        "language": "English",
        "publisher": "Alfred A. Knopf",
        "genre": "Memoir, Adventure",
        "availability": "available",
        "location": "I-09-NF",
        "description": "From lost to found on the Pacific Crest Trail."
      },
      {
        "id": "NF027",
        "title": "The Omnivore's Dilemma",
        "author": "Michael Pollan",
        "isbn": "978-0-14-303858-6",
        "image": "http://books.google.com/books/content?id=kPlLwAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 2006,
        "pages": 464,
        "language": "English",
        "publisher": "Penguin Press",
        "genre": "Food, Environment",
        "availability": "available",
        "location": "J-01-NF",
        "description": "A natural history of four meals."
      },
      {
        "id": "NF028",
        "title": "Fast Food Nation",
        "author": "Eric Schlosser",
        "isbn": "978-0-547-75033-0",
        "image": "http://books.google.com/books/content?id=dU13X_AM_N8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2001,
        "pages": 383,
        "language": "English",
        "publisher": "Houghton Mifflin",
        "genre": "Food, Social Criticism",
        "availability": "available",
        "location": "J-05-NF",
        "description": "The dark side of the all-American meal."
      },
      {
        "id": "NF029",
        "title": "Blink",
        "author": "Malcolm Gladwell",
        "isbn": "978-0-316-01066-5",
        "image": "http://books.google.com/books/content?id=FiPLHNvT_NkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2005,
        "pages": 296,
        "language": "English",
        "publisher": "Little, Brown and Company",
        "genre": "Psychology, Decision Making",
        "availability": "checked_out",
        "location": "J-09-NF",
        "description": "The power of thinking without thinking."
      },
      {
        "id": "NF030",
        "title": "The Glass Castle",
        "author": "Jeannette Walls",
        "isbn": "978-0-7432-4753-7",
        "image": "http://books.google.com/books/content?id=g5zvjwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.3,
        "year_published": 2005,
        "pages": 288,
        "language": "English",
        "publisher": "Scribner",
        "genre": "Memoir, Family",
        "availability": "available",
        "location": "K-02-NF",
        "description": "A memoir of resilience and redemption from an unconventional childhood."
      }
    ],
    "sci_fi": [
      {
        "id": "SF001",
        "title": "Dune",
        "author": "Frank Herbert",
        "isbn": "978-0-441-17271-9",
        "image": "http://books.google.com/books/content?id=iAblDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.3,
        "year_published": 1965,
        "pages": 688,
        "language": "English",
        "publisher": "Chilton Books",
        "genre": "Space Opera, Political Fiction",
        "availability": "available",
        "location": "A-01-SF",
        "description": "Paul Atreides's journey on the desert planet Arrakis and the spice melange."
      },
      {
        "id": "SF002",
        "title": "Foundation",
        "author": "Isaac Asimov",
        "isbn": "978-0-553-29335-5",
        "image": "http://books.google.com/books/content?id=9PCAPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1951,
        "pages": 244,
        "language": "English",
        "publisher": "Gnome Press",
        "genre": "Space Opera, Hard Science Fiction",
        "availability": "available",
        "location": "A-05-SF",
        "description": "Psychohistory and the fall of the Galactic Empire."
      },
      {
        "id": "SF003",
        "title": "Neuromancer",
        "author": "William Gibson",
        "isbn": "978-0-441-56956-9",
        "image": "http://books.google.com/books/content?id=QMBLHMv-k6oC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 3.9,
        "year_published": 1984,
        "pages": 271,
        "language": "English",
        "publisher": "Ace Books",
        "genre": "Cyberpunk",
        "availability": "checked_out",
        "location": "A-09-SF",
        "description": "The pioneering cyberpunk novel about hackers and artificial intelligence."
      },
      {
        "id": "SF004",
        "title": "The Hitchhiker's Guide to the Galaxy",
        "author": "Douglas Adams",
        "isbn": "978-0-345-39180-3",
        "image": "http://books.google.com/books/content?id=Fu2VnsEW8S0C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1979,
        "pages": 193,
        "language": "English",
        "publisher": "Pan Books",
        "genre": "Comic Science Fiction",
        "availability": "available",
        "location": "B-03-SF",
        "description": "Arthur Dent's intergalactic adventures after Earth's destruction."
      },
      {
        "id": "SF005",
        "title": "Ender's Game",
        "author": "Orson Scott Card",
        "isbn": "978-0-812-55070-2",
        "image": "http://books.google.com/books/content?id=_ZghmgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.3,
        "year_published": 1985,
        "pages": 324,
        "language": "English",
        "publisher": "Tor Books",
        "genre": "Military Science Fiction",
        "availability": "available",
        "location": "B-07-SF",
        "description": "A child prodigy trained to fight an alien invasion."
      },
      {
        "id": "SF006",
        "title": "The Time Machine",
        "author": "H.G. Wells",
        "isbn": "978-0-486-28472-0",
        "image": "http://books.google.com/books/content?id=IMHXDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1895,
        "pages": 118,
        "language": "English",
        "publisher": "William Heinemann",
        "genre": "Time Travel, Social Science Fiction",
        "availability": "available",
        "location": "B-11-SF",
        "description": "A Victorian scientist's journey into the far future."
      },
      {
        "id": "SF007",
        "title": "Fahrenheit 451",
        "author": "Ray Bradbury",
        "isbn": "978-1-4516-7331-9",
        "image": "http://books.google.com/books/content?id=b-o_K_AFJiUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1953,
        "pages": 249,
        "language": "English",
        "publisher": "Ballantine Books",
        "genre": "Dystopian Science Fiction",
        "availability": "available",
        "location": "C-04-SF",
        "description": "A fireman's awakening in a society where books are burned."
      },
      {
        "id": "SF008",
        "title": "The War of the Worlds",
        "author": "H.G. Wells",
        "isbn": "978-0-486-29506-1",
        "image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320391644i/8909.jpg",
        "rating": 3.8,
        "year_published": 1898,
        "pages": 192,
        "language": "English",
        "publisher": "William Heinemann",
        "genre": "Alien Invasion, Military Science Fiction",
        "availability": "available",
        "location": "C-08-SF",
        "description": "Martians invade Earth with superior technology."
      },
      {
        "id": "SF009",
        "title": "I, Robot",
        "author": "Isaac Asimov",
        "isbn": "978-0-553-29438-3",
        "image": "http://books.google.com/books/content?id=MD0GAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.2,
        "year_published": 1950,
        "pages": 253,
        "language": "English",
        "publisher": "Gnome Press",
        "genre": "Robot Fiction, Hard Science Fiction",
        "availability": "checked_out",
        "location": "C-12-SF",
        "description": "Stories exploring the Three Laws of Robotics."
      },
      {
        "id": "SF010",
        "title": "Blade Runner (Do Androids Dream of Electric Sheep?)",
        "author": "Philip K. Dick",
        "isbn": "978-0-345-40447-6",
        "image": "http://books.google.com/books/content?id=BzMyAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1968,
        "pages": 210,
        "language": "English",
        "publisher": "Doubleday",
        "genre": "Cyberpunk, Philosophical Science Fiction",
        "availability": "available",
        "location": "D-05-SF",
        "description": "A bounty hunter tracks down rogue androids in post-apocalyptic Earth."
      },
      {
        "id": "SF011",
        "title": "The Martian",
        "author": "Andy Weir",
        "isbn": "978-0-8041-3902-1",
        "image": "http://books.google.com/books/content?id=RLDSDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.4,
        "year_published": 2011,
        "pages": 369,
        "language": "English",
        "publisher": "Crown Publishers",
        "genre": "Hard Science Fiction, Survival",
        "availability": "available",
        "location": "D-09-SF",
        "description": "An astronaut's struggle to survive alone on Mars."
      },
      {
        "id": "SF012",
        "title": "Stranger in a Strange Land",
        "author": "Robert A. Heinlein",
        "isbn": "978-0-441-79034-0",
        "image": "http://books.google.com/books/content?id=naPjEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 1961,
        "pages": 525,
        "language": "English",
        "publisher": "Putnam Publishing Group",
        "genre": "Social Science Fiction",
        "availability": "available",
        "location": "E-01-SF",
        "description": "A human raised by Martians returns to Earth."
      },
      {
        "id": "SF013",
        "title": "The Left Hand of Darkness",
        "author": "Ursula K. Le Guin",
        "isbn": "978-0-441-47812-5",
        "image": "http://books.google.com/books/content?id=aq0OAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1969,
        "pages": 304,
        "language": "English",
        "publisher": "Ace Books",
        "genre": "Social Science Fiction, Gender Studies",
        "availability": "available",
        "location": "E-05-SF",
        "description": "An envoy's mission to a planet where inhabitants can change gender."
      },
      {
        "id": "SF014",
        "title": "Hyperion",
        "author": "Dan Simmons",
        "isbn": "978-0-553-28368-5",
        "image": "http://books.google.com/books/content?id=TOMDq0vqXIQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.2,
        "year_published": 1989,
        "pages": 512,
        "language": "English",
        "publisher": "Doubleday",
        "genre": "Space Opera, Literary Science Fiction",
        "availability": "available",
        "location": "E-09-SF",
        "description": "Pilgrims journey to the mysterious world of Hyperion."
      },
      {
        "id": "SF015",
        "title": "Snow Crash",
        "author": "Neal Stephenson",
        "isbn": "978-0-553-08853-5",
        "image": "http://books.google.com/books/content?id=SXyqPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4,
        "year_published": 1992,
        "pages": 440,
        "language": "English",
        "publisher": "Bantam Books",
        "genre": "Cyberpunk, Post-Cyberpunk",
        "availability": "checked_out",
        "location": "F-02-SF",
        "description": "A hacker investigates a computer virus in virtual reality."
      },
      {
        "id": "SF016",
        "title": "The Stars My Destination",
        "author": "Alfred Bester",
        "isbn": "978-0-679-76784-5",
        "image": "http://books.google.com/books/content?id=BXEgAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1956,
        "pages": 258,
        "language": "English",
        "publisher": "Signet Books",
        "genre": "Space Opera, Teleportation Fiction",
        "availability": "available",
        "location": "F-06-SF",
        "description": "A man's quest for revenge in a world where teleportation is possible."
      },
      {
        "id": "SF017",
        "title": "Starship Troopers",
        "author": "Robert A. Heinlein",
        "isbn": "978-0-441-78358-8",
        "image": "http://books.google.com/books/content?id=1lK3xA72adAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4,
        "year_published": 1959,
        "pages": 263,
        "language": "English",
        "publisher": "G.P. Putnam's Sons",
        "genre": "Military Science Fiction",
        "availability": "available",
        "location": "F-10-SF",
        "description": "A soldier's experience fighting alien bugs in powered armor."
      },
      {
        "id": "SF018",
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "isbn": "978-0-385-49081-8",
        "image": "http://books.google.com/books/content?id=UZs9sbk5gO0C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.1,
        "year_published": 1985,
        "pages": 311,
        "language": "English",
        "publisher": "McClelland & Stewart",
        "genre": "Dystopian Science Fiction",
        "availability": "available",
        "location": "G-03-SF",
        "description": "A dystopian future where women are subjugated for reproduction."
      },
      {
        "id": "SF019",
        "title": "Ready Player One",
        "author": "Ernest Cline",
        "isbn": "978-0-307-88743-6",
        "image": "http://books.google.com/books/content?id=x7P3LQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4.3,
        "year_published": 2011,
        "pages": 374,
        "language": "English",
        "publisher": "Crown Publishing Group",
        "genre": "Science Fiction, Dystopian",
        "availability": "available",
        "location": "G-04-SF",
        "description": "In a dystopian 2045, Wade Watts embarks on a quest within a virtual reality universe to find an Easter egg that promises unimaginable wealth and control over the OASIS."
      },
      {
        "id": "SF020",
        "title": "The Expanse: Leviathan Wakes",
        "author": "James S.A. Corey",
        "isbn": "978-0-316-12908-4",
        "image": "http://books.google.com/books/content?id=-iB-1sc02DgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.2,
        "year_published": 2011,
        "pages": 561,
        "language": "English",
        "publisher": "Orbit Books",
        "genre": "Space Opera, Hard Science Fiction",
        "availability": "available",
        "location": "G-11-SF",
        "description": "Political intrigue and alien technology in the solar system."
      },
      {
        "id": "SF021",
        "title": "Childhood's End",
        "author": "Arthur C. Clarke",
        "isbn": "978-0-345-44405-9",
        "image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320552628i/414999.jpg",
        "rating": 4,
        "year_published": 1953,
        "pages": 224,
        "language": "English",
        "publisher": "Ballantine Books",
        "genre": "First Contact, Transcendence",
        "availability": "checked_out",
        "location": "H-04-SF",
        "description": "Mysterious aliens oversee humanity's evolution."
      },
      {
        "id": "SF022",
        "title": "The Road",
        "author": "Cormac McCarthy",
        "isbn": "978-0-307-47431-9",
        "image": "http://books.google.com/books/content?id=WIKrD-GKehQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2006,
        "pages": 287,
        "language": "English",
        "publisher": "Alfred A. Knopf",
        "genre": "Post-Apocalyptic",
        "availability": "available",
        "location": "H-08-SF",
        "description": "A father and son's journey through a post-apocalyptic wasteland."
      },
      {
        "id": "SF023",
        "title": "Contact",
        "author": "Carl Sagan",
        "isbn": "978-0-671-00410-4",
        "image": "http://books.google.com/books/content?id=pO6mDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1985,
        "pages": 432,
        "language": "English",
        "publisher": "Simon & Schuster",
        "genre": "Hard Science Fiction, First Contact",
        "availability": "available",
        "location": "H-12-SF",
        "description": "Scientists receive and decode messages from extraterrestrial intelligence."
      },
      {
        "id": "SF024",
        "title": "The Giver",
        "author": "Lois Lowry",
        "isbn": "978-0-544-33626-0",
        "image": "http://books.google.com/books/content?id=hKN9xV-xl2kC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.1,
        "year_published": 1993,
        "pages": 208,
        "language": "English",
        "publisher": "Houghton Mifflin",
        "genre": "Dystopian, Young Adult",
        "availability": "available",
        "location": "I-05-SF",
        "description": "A boy discovers the dark truth about his seemingly perfect society."
      },
      {
        "id": "SF025",
        "title": "Jurassic Park",
        "author": "Michael Crichton",
        "isbn": "978-0-345-37077-8",
        "image": "http://books.google.com/books/content?id=V5s14nks9I8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 4.2,
        "year_published": 1990,
        "pages": 399,
        "language": "English",
        "publisher": "Alfred A. Knopf",
        "genre": "Genetic Engineering, Thriller",
        "availability": "available",
        "location": "I-09-SF",
        "description": "Genetically recreated dinosaurs threaten visitors to a theme park."
      },
      {
        "id": "SF026",
        "title": "A Clockwork Orange",
        "author": "Anthony Burgess",
        "isbn": "978-0-393-31283-6",
        "image": "http://books.google.com/books/content?id=F-rToAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 3.9,
        "year_published": 1962,
        "pages": 192,
        "language": "English",
        "publisher": "William Heinemann",
        "genre": "Dystopian, Social Science Fiction",
        "availability": "available",
        "location": "J-02-SF",
        "description": "A violent youth undergoes experimental psychological conditioning."
      },
      {
        "id": "SF027",
        "title": "The Caves of Steel",
        "author": "Isaac Asimov",
        "isbn": "978-0-553-29340-9",
        "image": "http://books.google.com/books/content?id=UApoDl860F4C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "rating": 4,
        "year_published": 1954,
        "pages": 206,
        "language": "English",
        "publisher": "Doubleday",
        "genre": "Detective Fiction, Robot Fiction",
        "availability": "available",
        "location": "J-06-SF",
        "description": "A detective partners with a robot to solve a murder in a domed city."
      },
      {
        "id": "SF028",
        "title": "The Invisible Man",
        "author": "H.G. Wells",
        "isbn": "978-0-486-27071-6",
        "image": "http://books.google.com/books/content?id=vdAOAAAAIAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.6,
        "year_published": 1897,
        "pages": 151,
        "language": "English",
        "publisher": "C. Arthur Pearson",
        "genre": "Scientific Romance",
        "availability": "checked_out",
        "location": "J-10-SF",
        "description": "A scientist discovers the secret of invisibility with dangerous consequences."
      },
      {
        "id": "SF029",
        "title": "Oryx and Crake",
        "author": "Margaret Atwood",
        "isbn": "978-0-385-50385-7",
        "image": "http://books.google.com/books/content?id=NljT2Bn3Y-wC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.9,
        "year_published": 2003,
        "pages": 376,
        "language": "English",
        "publisher": "McClelland & Stewart",
        "genre": "Post-Apocalyptic, Genetic Engineering",
        "availability": "available",
        "location": "K-01-SF",
        "description": "A post-pandemic world where genetic engineering has gone wrong."
      },
      {
        "id": "SF030",
        "title": "Red Mars",
        "author": "Kim Stanley Robinson",
        "isbn": "978-0-553-56073-9",
        "image": "http://books.google.com/books/content?id=OVTX6eVzpQ0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
        "rating": 3.8,
        "year_published": 1992,
        "pages": 572,
        "language": "English",
        "publisher": "Bantam Spectra",
        "genre": "Hard Science Fiction, Terraforming",
        "availability": "available",
        "location": "K-05-SF",
        "description": "The first hundred colonists attempt to terraform Mars."
      }
    ]
  }

  export default BookData;